### ISSUE TITLE
Average load of 1.30 on the cubieboard?

### ISSUE THREAD

**Issue by sachilles** [cubieplayer/Cubian#183]
Dear all,

first of all I would like to thank you for this nice work and maintaining cubian. But since the last update of cubian a friend of my and me realized an average load of 1.30 on the cubieboard (monitored using monitorix) and in addition, the nandd process takes a lot of cpu time (in my case ~ 35 min. while having an uptime of ~ 2 days). Could you explain what exactly the nandd process does and why does this process takes such a huge amount of cpu time since the last update?

Is this a usual behavior? (We never saw this behavior before.)

Best regards and thanks in advance

**Comment by cubieplayer** [comment]
What's your board, cb1 or cb2? and what's the kernel version?

**Comment by sachilles** [comment]
Sorry, I forgot to mention. It's a cubieboard 1 and the kernel version is 3.4.61+ #39.

**Comment by cubieplayer** [comment]
I noticed this issue aslo, the 3.4.43 kernel has a load average 0.5, but when i switch to 3.4.61, it becomes to 1.30. I don't know the reason but you can switch to use 3.4.43 to solve the problem temporarily. To revert the kernel, you need to execute `cubian-update --revert-firmware` mutiple times.

**Comment by cubieplayer** [comment]
I can now confirm this issue is caused by the SUNXI USB2.0 Dual Role Controller driver, After i [disabled this driver](https://github.com/mmplayer/sunxi-kernel-config/commit/e28c3c30afe585ec04a3c3fdd0646a7a220fd2da), The load average droped to 0.01 which is very nice for us.I will push the update to server later. You can fix the problem via cubian-update soon.  
![screenshot from 2013-11-03 05 04 52](https://f.cloud.github.com/assets/4461036/1459950/78681e34-4403-11e3-8ffa-ecb11c931d0e.png)

**Comment by sachilles** [comment]
These are really good news. Thank you very much.

**Comment by oguska** [comment]
Issue still exist with kernel 3.4.79-sun4i

**Comment by michalliu** [comment]
Please apply this patch to your script.bin, I believe the problem should be solved.
https://github.com/mmplayer/sunxi-boards/commit/1a25403327eae516a5826e46baca1bab349e001a#diff-33c130ace86127ccf8a58a380bae3e89

**Comment by michalliu** [comment]
see aslo #241

**Comment by sachilles** [comment]
Hi,

it's true that this issue still exists. Besides applying the path above your could also simply "fix" your script.fex. This script can be converted from the binary format by `bin2fex` and after some modifications to the binary format by means of `fex2bin`. (For more details I refer to http://linux-sunxi.org/Sunxi-tools .)

What should be changed? You will find an entry like

```
[usbc0]
usb_used = 1
usb_port_type = 2
usb_detect_type = 1
usb_id_gpio = port:PH04<0><1><default><default>
usb_det_vbus_gpio = port:PH05<0><0><default><default>
usb_drv_vbus_gpio = port:PB09<1><0><default><0>
usb_host_init_state = 0
```

By deactivating the OTG, i.e. using

```
[usbc0]
usb_used = 0
usb_port_type = 2
usb_detect_type = 1
usb_id_gpio = port:PH04<0><1><default><default>
usb_det_vbus_gpio = port:PH05<0><0><default><default>
usb_drv_vbus_gpio = port:PB09<1><0><default><0>
usb_host_init_state = 0
```

the high load will vanish. (At least this worked for me.)

**Comment by mzapa** [comment]
Greetings,

I collaborated with Pat Wood on this subject during the v3.4.75 pre-release.  I discovered that configuring OTG for device mode only support in the fex/bin disables OTG mass storage support but will support RNDIS networking via g_ether.  My requirements did not include OTG mass storage support and the change did not require re-compiling the kernel.  The load averages become normal and OTG networking functioned perfectly.  More info can be found in the thread at http://www.cubieforums.com/index.php/topic,1413.msg9464.html#msg9464
