### ISSUE TITLE
TL-WN722N not working

### ISSUE THREAD

**Issue by POMATu** [cubieplayer/Cubian#230]
Hi,

This dongle do not work. I just wrote cubie image to sdcard and ran cubian-update. 
The led on this wifi dongle do not blink.

root@Cubian:/home/cubie# lsmod
Module                  Size  Used by
mali                  119417  0 
ump                    58137  1 mali
gpio_sunxi              8675  0 

root@Cubian:/home/cubie# iwconfig
lo        no wireless extensions.

tunl0     no wireless extensions.

eth0      no wireless extensions.

root@Cubian:/home/cubie# modprobe ath9k_htc
FATAL: Module ath9k_htc not found.

Is it possibe to use this dongle with cubian?
Thanks

**Comment by faker00t** [comment]
You need to install firmware package for atheros (apt-get install firmware-atheros).

**Comment by POMATu** [comment]
root@Cubian:/home/cubie# apt-get install firmware-atheros
Reading package lists... Done
Building dependency tree  
Reading state information... Done
firmware-atheros is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 30 not upgraded.
root@Cubian:/home/cubie# iwconfig
lo        no wireless extensions.

tunl0     no wireless extensions.

eth0      no wireless extensions.

it's already installed. Adapter still not working. Tried to insert it after boot, and boot with adapter inserted - no luck.

**Comment by faker00t** [comment]
What about modprobe ath9k (not ath9k_htc)?

**Comment by POMATu** [comment]
root@Cubian:/home/cubie# modprobe ath9k
root@Cubian:/home/cubie# modprobe ath9k_htc
FATAL: Module ath9k_htc not found.
root@Cubian:/home/cubie# iwconfig
lo        no wireless extensions.

tunl0     no wireless extensions.

eth0      no wireless extensions.

root@Cubian:/home/cubie# cat /etc/network/interfaces 

auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp

auto wlan0
allow-hotplug wlan0
iface wlan0 inet manual

Also need to mention that Wi-Pi dongle is working okay.

**Comment by toketin** [comment]
Firmware-atheros is present by default in Cubian (r8), but maybe the kernel need to be compiled with "ath9k_htc" support in order to make it working:

cubie@Cubian:~$ modprobe ath9k_htc
FATAL: Module ath9k_htc not found.

So please add it in a future release. Thanks

**Comment by POMATu** [comment]
tried to compile it on the cubieboard without success.

Temporary switched to Archlinux arm. It is the only distribution that has ath9k_htc now (I think I tried EVERY distribution for cubieboard). But archlinux has systemd and netctl crap in it, and also hdmi is not working there, so  I am waiting for the next cubian release.

Please compile that module in the next release, or make an kernel update for "cubian-update". Really A LOT OF usb wifi adapters are not working now. Thanks.

**Comment by toketin** [comment]
@POMATu i confirm that under Arch Arm our wifi dongle usb is recognized without problem. I'm trying Cubian now, because i want to try XBMC here, since under Arch, i compiled it without X support, but the 720p videos are laggy and the sound is not working. If you want i'm in #cubian chan in freenode.net, log you too!

**Comment by toketin** [comment]
Hi, i fixed the issue! I tried first to compile the firmware following this guide: https://wiki.debian.org/ath9k_htc/open_firmware it took a lot of time for "make toolchain", i finally build the firmware htc_9271.fw, moved it into /lib/firmware but the module needed "ath9k_htc" still didn't exist. 
So i searched how to compile manually the linux-sun4i kernel and i found this interesting site: https://romanrm.net/a10/kernel which has also the giude to compile the customizd kernel and this cool repository with some precompiled kernels. I installed the 3.4.75-r0-s-rm4+, moved its uImage to /boot partition (with a backup of the older one), rebooted and finally the Tp Wn722n was recognized by Debian, that correctly loaded the ath9k_htc module.
Now i've configured wicd (using wicd-curses) the connection to the wireless AP because with the simple /etc/network/interfaces i wasn't able to connect it.

**Comment by michalliu** [comment]
Thanks for share

**Comment by POMATu** [comment]
Ok, more than half a year passed, cubian X1 is released, but ath9k_htc is still not there. 

Why do you point all users to this issue? why cant you include this module in the build? A lot of wlan dongles dont work with cubian because this module is not included! 

I know I cant demand you to do anything, but isn't your goal to do complete firmware for cubieboard like raspbian for raspberry pi? I am not asking you to include legacy printer driver for some old-school LPT printer, I just ask to make the usual things for any linux distribution to work.

Yes I can compile module myself, but I have to do that for every new Cubian release, and many other users can't do that due to lack of experience. This is not the solution.

`root@Cubian:/home/cubie# modprobe ath9k_htc`
`FATAL: Module ath9k_htc not found.`

This issue is not solved

**Comment by alex3kov** [comment]
I agree with @POMATu. Spent half a day looking for solution before finding the above workaround. Given the availability of ath9k_htc modules and open source firmware (no closed binary blobs), this dongle should be plug-and-play.
