### ISSUE TITLE
HDD power issue

### ISSUE THREAD

**Issue by s-kostyuk** [cubieplayer/Cubian#83]
Good day

After update to the last cubian version (through cubian-update, Linux Cubian 3.4.43+ # 13 PREEMPT 28 Aug 03:31:15 CST) I noticed one new feature. Cubieboard on start activates power for HDD (SATA 5V connector) only for three seconds and then disables it. So HDD can't start and it's problem. How to turn on HDD power connector again or increase time of HDD start waiting? Sorry for my English, video illustration: http://youtu.be/L68rOXMsdes, system start log with connected 2.5" SATA hard disk drive: http://dpaste.com/hold/1360917/. Thanks

**Comment by cubieplayer** [comment]
Thanks for reporting this problem. The very detailed boot logs and video are helpful.

**Comment by cubieplayer** [comment]
Hi, this problem has been solved. https://github.com/cubieplayer/Cubian/issues/100

**Comment by 346L3** [comment]
I'm still having issues with SATA-power. I manually applied the fix listed at the other issue, but the error is still the same: The disk spins up normally, but when the cubieboard finished booting, after a few seconds the drive turns off (powerloss) and tries to spin up in fast succession. It sounds (don't have a multimeter at hand) as if SATA-power turns off for a fraction of a second 1-2 times per second. script.bin is fixed as you did on github, bootlog confirms that I2S has no active instances... Can this problem be related or should I open a new bug... and - most important - any ideas how I can debug it?

**Comment by mmplayer** [comment]
@346L3 I thought you need a power which output is 5V 2A

**Comment by 346L3** [comment]
@mmplayer I don't think that's the issue. I'm using a 5V/2A PSU and the same disk in a USB enclosure functions happily on what's essentially the same 5V source minus the SATA power control...

**Comment by cubieplayer** [comment]
@346L3 have you tried a SSD? What brand is your hard disk?

**Comment by 346L3** [comment]
@cubieplayer I can try a SSD tomorrow. I'm not at home currently, so the HDD is the only SATA device in reach. It's a Toshiba MQ01ABD100. I'll report if I find something

**Comment by hawk0107** [comment]
Hi all, Today (September14th) the fixed script.bin will not be downloaded by the cubian-update. the version is from September 4th. But the fix from September 9th. I fixed it by modifing the script.fex file on /boot (https://github.com/mmplayer/sunxi-boards/commit/7bb2feaaf6257eee80d7896c095482ec01952ad8) and with that created the modified script.bin with fex2bin (https://www.olimex.com/forum/index.php?topic=184.0). 

@cubieplayer 
thank you very much for your great work on cubian. 
You only need to check why there is no new script.bin downloaded by cubian-update

**Comment by 346L3** [comment]
@hawk0107 I did the same (can't use cubian-update currently out of fear it'll break a wireless module i compiled) and my bootlog clearly said that i2s has no activated devices... I'm not sure my problem is related, but the fix didn't help ;)
I still haven't tested with SSD, but can this evening, I hope.

**Comment by cubieplayer** [comment]
@hawk0107 thanks for your work, it seems that the sata and i2s are confilicts, you can't enable them both on script.bin.
